test_upper_case_names (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_upper_case_names (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 17, in test_upper_case_names
    output = list(map(exercice.majuscule, altered_words))
  File "/home/runner/work/c03_ch2_ecriture-Zabiullah-sz/c03_ch2_ecriture-Zabiullah-sz/exercice.py", line 6, in majuscule
    lettre += 32
TypeError: must be str, not int

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
